# Generated by Django 4.0.5 on 2022-07-02 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import givito.service.models
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRegistrant',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('offering_price', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('offering_duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('registrant_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('expected_duration', models.DurationField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='UNASSIGNED', max_length=11)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('placeholder', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=givito.service.models.upload_placeholder, verbose_name='File foto')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
