# Generated by Django 4.0.5 on 2022-07-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectregistrant',
            name='project',
            field=models.ForeignKey(default='4803b5d4-0bfe-42d7-8d15-ff346ddf08e5', on_delete=django.db.models.deletion.CASCADE, to='service.project'),
            preserve_default=False,
        ),
    ]
