# Generated by Django 4.0.5 on 2022-07-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_projectregistrant_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectregistrant',
            old_name='user',
            new_name='owner',
        ),
    ]
