# Generated by Django 4.0.5 on 2022-07-02 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0005_rename_user_projectregistrant_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='registrant_uuid',
            new_name='registrant',
        ),
        migrations.RemoveField(
            model_name='projectregistrant',
            name='status',
        ),
        migrations.AlterField(
            model_name='projectregistrant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectregistrant',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrants', to='service.project'),
        ),
    ]
